# Generated by Django 5.0 on 2024-02-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opv_2d', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NorthForecastDiffuseRecord',
        ),
        migrations.DeleteModel(
            name='NorthForecastIonsRecord',
        ),
        migrations.DeleteModel(
            name='NorthForecastMonoRecord',
        ),
        migrations.DeleteModel(
            name='NorthForecastTotalRecord',
        ),
        migrations.DeleteModel(
            name='NorthForecastWaveRecord',
        ),
        migrations.DeleteModel(
            name='NorthNowcastDiffuseRecord',
        ),
        migrations.DeleteModel(
            name='NorthNowcastIonsRecord',
        ),
        migrations.DeleteModel(
            name='NorthNowcastMonoRecord',
        ),
        migrations.DeleteModel(
            name='NorthNowcastTotalRecord',
        ),
        migrations.DeleteModel(
            name='NorthNowcastWaveRecord',
        ),
        migrations.DeleteModel(
            name='SouthForecastDiffuseRecord',
        ),
        migrations.DeleteModel(
            name='SouthForecastIonsRecord',
        ),
        migrations.DeleteModel(
            name='SouthForecastMonoRecord',
        ),
        migrations.DeleteModel(
            name='SouthForecastTotalRecord',
        ),
        migrations.DeleteModel(
            name='SouthForecastWaveRecord',
        ),
        migrations.DeleteModel(
            name='SouthNowcastDiffuseRecord',
        ),
        migrations.DeleteModel(
            name='SouthNowcastIonsRecord',
        ),
        migrations.DeleteModel(
            name='SouthNowcastMonoRecord',
        ),
        migrations.DeleteModel(
            name='SouthNowcastTotalRecord',
        ),
        migrations.DeleteModel(
            name='SouthNowcastWaveRecord',
        ),
    ]
